# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0HJB5jJZc0YpEppgIvT7CKoK5AI7yOH
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
都道府県・市区町村選択ツール v33.0 (Streamlit Cloud対応版)
メインアプリケーション
"""

import streamlit as st
from src.data_loader import PrefectureCitySelector
from config.settings import APP_CONFIG

# ページ設定
st.set_page_config(
    page_title=APP_CONFIG["title"],
    page_icon=APP_CONFIG["icon"],
    layout=APP_CONFIG["layout"],
    initial_sidebar_state=APP_CONFIG["sidebar_state"]
)

def main():
    """メイン関数"""
    try:
        app = PrefectureCitySelector()
        app.run()
    except Exception as e:
        st.error(f"アプリケーションエラー: {str(e)}")
        st.info("ページを再読み込みしてください。")

if __name__ == "__main__":
    main()