# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0HJB5jJZc0YpEppgIvT7CKoK5AI7yOH

Package initialization
"""