# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0HJB5jJZc0YpEppgIvT7CKoK5AI7yOH
"""

python"""
アプリケーション設定
"""

APP_CONFIG = {
    "title": "都道府県・市区町村選択ツール v33.0",
    "icon": "🏛️",
    "layout": "wide",
    "sidebar_state": "expanded",
    "version": "33.0"
}

GITHUB_CONFIG = {
    "user_agent": "PrefectureCitySelector/33.0",
    "timeout": 30,
    "default_url": "https://raw.githubusercontent.com/USERNAME/REPOSITORY/main/000925835.xlsx"
}

GIS_CONFIG = {
    "supported_extensions": ['.zip', '.shp', '.shx', '.prj', '.dbf', '.cpg', '.kml'],
    "shapefile_required": ['.shp', '.shx', '.dbf']
}